// This file is auto-generated by @hey-api/openapi-ts

export type CustomGroupReadable = {
    readonly id: string;
    readonly member_count: number;
    readonly members: Array<CustomMembers>;
    name: string;
    description?: string | null;
    hidden?: boolean;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type CustomGroupWritable = {
    name: string;
    description?: string | null;
    hidden?: boolean;
    parent?: string | null;
};

export type CustomMembers = {
    readonly id: string;
    readonly email: string;
    readonly avatar: string;
    readonly first_name: string;
    readonly last_name: string;
    readonly date_joined: string;
};

export type CustomUserReadable = {
    readonly id: string;
    /**
     * Email address
     */
    email: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
    readonly groups: Array<CustomUserGroup>;
    readonly date_joined: string;
};

export type CustomUserWritable = {
    /**
     * Email address
     */
    email: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
};

export type CustomUserGroup = {
    readonly id: string;
    readonly name: string;
};

export type EnvironmentReadable = {
    readonly id: string;
    name: string;
    readonly created: string;
    readonly updated: string;
    description?: string | null;
    url: string;
    pg_url: string;
    parent_org: string;
    auth_user: string;
    default_resource_group?: string | null;
};

export type EnvironmentWritable = {
    name: string;
    description?: string | null;
    url: string;
    pg_url: string;
    parent_org: string;
    auth_user: string;
    default_resource_group?: string | null;
};

export type NestedReadable = {
    readonly id: string;
    name: string;
    description?: string | null;
    hidden?: boolean;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type NestedWritable = {
    name: string;
    description?: string | null;
    hidden?: boolean;
    parent?: string | null;
};

export type OrganizationReadable = {
    readonly id: string;
    name: string;
    avatar?: string | null;
    host: string;
    readonly created: string;
    readonly updated: string;
    root: NestedReadable;
};

export type OrganizationWritable = {
    name: string;
    avatar?: string | null;
    host: string;
    root: NestedWritable;
};

export type PaginatedCustomGroupListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomGroupReadable>;
};

export type PaginatedCustomGroupListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomGroupWritable>;
};

export type PaginatedCustomUserListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomUserReadable>;
};

export type PaginatedCustomUserListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomUserWritable>;
};

export type PaginatedEnvironmentListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<EnvironmentReadable>;
};

export type PaginatedEnvironmentListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<EnvironmentWritable>;
};

export type PaginatedOrganizationListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<OrganizationReadable>;
};

export type PaginatedOrganizationListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<OrganizationWritable>;
};

export type PaginatedResourcePermissionListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourcePermissionReadable>;
};

export type PaginatedResourcePermissionListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourcePermissionWritable>;
};

export type PaginatedResourceUserGroupListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserGroupReadable>;
};

export type PaginatedResourceUserGroupListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserGroupWritable>;
};

export type PaginatedResourceUserListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserReadable>;
};

export type PaginatedResourceUserListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserWritable>;
};

export type PaginatedResourceUserPermissionListReadable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserPermissionReadable>;
};

export type PaginatedResourceUserPermissionListWritable = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserPermissionWritable>;
};

export type PatchedCustomGroupReadable = {
    readonly id?: string;
    readonly member_count?: number;
    readonly members?: Array<CustomMembers>;
    name?: string;
    description?: string | null;
    hidden?: boolean;
    readonly created?: string;
    readonly updated?: string;
    parent?: string | null;
};

export type PatchedCustomGroupWritable = {
    name?: string;
    description?: string | null;
    hidden?: boolean;
    parent?: string | null;
};

export type PatchedCustomUserReadable = {
    readonly id?: string;
    /**
     * Email address
     */
    email?: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
    readonly groups?: Array<CustomUserGroup>;
    readonly date_joined?: string;
};

export type PatchedCustomUserWritable = {
    /**
     * Email address
     */
    email?: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
};

export type PatchedEnvironmentReadable = {
    readonly id?: string;
    name?: string;
    readonly created?: string;
    readonly updated?: string;
    description?: string | null;
    url?: string;
    pg_url?: string;
    parent_org?: string;
    auth_user?: string;
    default_resource_group?: string | null;
};

export type PatchedEnvironmentWritable = {
    name?: string;
    description?: string | null;
    url?: string;
    pg_url?: string;
    parent_org?: string;
    auth_user?: string;
    default_resource_group?: string | null;
};

export type PatchedOrganizationReadable = {
    readonly id?: string;
    name?: string;
    avatar?: string | null;
    host?: string;
    readonly created?: string;
    readonly updated?: string;
    root?: NestedReadable;
};

export type PatchedOrganizationWritable = {
    name?: string;
    avatar?: string | null;
    host?: string;
    root?: NestedWritable;
};

export type PatchedResourcePermissionReadable = {
    readonly id?: string;
    resource_id?: string;
    inherit_from_parent?: boolean;
    readonly created?: string;
    readonly updated?: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource?: string;
    group?: string | null;
};

export type PatchedResourcePermissionWritable = {
    resource_id?: string;
    inherit_from_parent?: boolean;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource?: string;
    group?: string | null;
};

export type PatchedResourceUserGroupReadable = {
    readonly id?: string;
    readonly environment?: string;
    name?: string;
    description?: string | null;
    readonly created?: string;
    readonly updated?: string;
    parent?: string | null;
};

export type PatchedResourceUserGroupWritable = {
    name?: string;
    description?: string | null;
    parent?: string | null;
};

export type ResourcePermissionReadable = {
    readonly id: string;
    resource_id: string;
    inherit_from_parent?: boolean;
    readonly created: string;
    readonly updated: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource: string;
    group?: string | null;
};

export type ResourcePermissionWritable = {
    resource_id: string;
    inherit_from_parent?: boolean;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource: string;
    group?: string | null;
};

export type ResourceUserReadable = {
    readonly id: string;
    user_id: string;
    readonly created: string;
    readonly groups: Array<ResourceUserGroupReadable>;
    readonly environment: string;
};

export type ResourceUserWritable = {
    user_id: string;
};

export type ResourceUserGroupReadable = {
    readonly id: string;
    readonly environment: string;
    name: string;
    description?: string | null;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type ResourceUserGroupWritable = {
    name: string;
    description?: string | null;
    parent?: string | null;
};

export type ResourceUserPermissionReadable = {
    readonly id: string;
    resource_id: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    user_id?: string | null;
};

export type ResourceUserPermissionWritable = {
    resource_id: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    user_id?: string | null;
};

/**
 * Used in :class:`durin.views.TokenSessionsViewSet`.
 *
 * .. versionadded:: 1.0.0
 */
export type TokenSessionsReadable = {
    readonly id: number;
    /**
     * A unique identification name for the client.
     */
    readonly client: string;
    readonly created: string;
    readonly expiry: string;
    /**
     * Dynamic property that returns ``True`` if token has expired,
     * otherwise ``False``.
     */
    readonly has_expired: boolean;
    readonly is_current: boolean;
    expires_in_str: string;
};

/**
 * Used in :class:`durin.views.TokenSessionsViewSet`.
 *
 * .. versionadded:: 1.0.0
 */
export type TokenSessionsWritable = {
    expires_in_str: string;
};

export type AccessControlEnvironmentsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/environments/';
};

export type AccessControlEnvironmentsListResponses = {
    200: PaginatedEnvironmentListReadable;
};

export type AccessControlEnvironmentsListResponse = AccessControlEnvironmentsListResponses[keyof AccessControlEnvironmentsListResponses];

export type AccessControlEnvironmentsCreateData = {
    body: EnvironmentWritable;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/environments/';
};

export type AccessControlEnvironmentsCreateResponses = {
    201: EnvironmentReadable;
};

export type AccessControlEnvironmentsCreateResponse = AccessControlEnvironmentsCreateResponses[keyof AccessControlEnvironmentsCreateResponses];

export type AccessControlEnvironmentsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/environments/{id}/';
};

export type AccessControlEnvironmentsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlEnvironmentsDestroyResponse = AccessControlEnvironmentsDestroyResponses[keyof AccessControlEnvironmentsDestroyResponses];

export type AccessControlEnvironmentsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/environments/{id}/';
};

export type AccessControlEnvironmentsRetrieveResponses = {
    200: EnvironmentReadable;
};

export type AccessControlEnvironmentsRetrieveResponse = AccessControlEnvironmentsRetrieveResponses[keyof AccessControlEnvironmentsRetrieveResponses];

export type AccessControlEnvironmentsPartialUpdateData = {
    body?: PatchedEnvironmentWritable;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/environments/{id}/';
};

export type AccessControlEnvironmentsPartialUpdateResponses = {
    200: EnvironmentReadable;
};

export type AccessControlEnvironmentsPartialUpdateResponse = AccessControlEnvironmentsPartialUpdateResponses[keyof AccessControlEnvironmentsPartialUpdateResponses];

export type AccessControlEnvironmentsUpdateData = {
    body: EnvironmentWritable;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/environments/{id}/';
};

export type AccessControlEnvironmentsUpdateResponses = {
    200: EnvironmentReadable;
};

export type AccessControlEnvironmentsUpdateResponse = AccessControlEnvironmentsUpdateResponses[keyof AccessControlEnvironmentsUpdateResponses];

export type AccessControlGroupsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/groups/';
};

export type AccessControlGroupsListResponses = {
    200: PaginatedResourceUserGroupListReadable;
};

export type AccessControlGroupsListResponse = AccessControlGroupsListResponses[keyof AccessControlGroupsListResponses];

export type AccessControlGroupsCreateData = {
    body: ResourceUserGroupWritable;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/groups/';
};

export type AccessControlGroupsCreateResponses = {
    201: ResourceUserGroupReadable;
};

export type AccessControlGroupsCreateResponse = AccessControlGroupsCreateResponses[keyof AccessControlGroupsCreateResponses];

export type AccessControlGroupsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlGroupsDestroyResponse = AccessControlGroupsDestroyResponses[keyof AccessControlGroupsDestroyResponses];

export type AccessControlGroupsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsRetrieveResponses = {
    200: ResourceUserGroupReadable;
};

export type AccessControlGroupsRetrieveResponse = AccessControlGroupsRetrieveResponses[keyof AccessControlGroupsRetrieveResponses];

export type AccessControlGroupsPartialUpdateData = {
    body?: PatchedResourceUserGroupWritable;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsPartialUpdateResponses = {
    200: ResourceUserGroupReadable;
};

export type AccessControlGroupsPartialUpdateResponse = AccessControlGroupsPartialUpdateResponses[keyof AccessControlGroupsPartialUpdateResponses];

export type AccessControlGroupsUpdateData = {
    body: ResourceUserGroupWritable;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsUpdateResponses = {
    200: ResourceUserGroupReadable;
};

export type AccessControlGroupsUpdateResponse = AccessControlGroupsUpdateResponses[keyof AccessControlGroupsUpdateResponses];

export type AccessControlPermissionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/permissions/';
};

export type AccessControlPermissionsListResponses = {
    200: PaginatedResourcePermissionListReadable;
};

export type AccessControlPermissionsListResponse = AccessControlPermissionsListResponses[keyof AccessControlPermissionsListResponses];

export type AccessControlPermissionsCreateData = {
    body: ResourcePermissionWritable;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/permissions/';
};

export type AccessControlPermissionsCreateResponses = {
    201: ResourcePermissionReadable;
};

export type AccessControlPermissionsCreateResponse = AccessControlPermissionsCreateResponses[keyof AccessControlPermissionsCreateResponses];

export type AccessControlPermissionsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlPermissionsDestroyResponse = AccessControlPermissionsDestroyResponses[keyof AccessControlPermissionsDestroyResponses];

export type AccessControlPermissionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsRetrieveResponses = {
    200: ResourcePermissionReadable;
};

export type AccessControlPermissionsRetrieveResponse = AccessControlPermissionsRetrieveResponses[keyof AccessControlPermissionsRetrieveResponses];

export type AccessControlPermissionsPartialUpdateData = {
    body?: PatchedResourcePermissionWritable;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsPartialUpdateResponses = {
    200: ResourcePermissionReadable;
};

export type AccessControlPermissionsPartialUpdateResponse = AccessControlPermissionsPartialUpdateResponses[keyof AccessControlPermissionsPartialUpdateResponses];

export type AccessControlPermissionsUpdateData = {
    body: ResourcePermissionWritable;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsUpdateResponses = {
    200: ResourcePermissionReadable;
};

export type AccessControlPermissionsUpdateResponse = AccessControlPermissionsUpdateResponses[keyof AccessControlPermissionsUpdateResponses];

export type AccessControlResourcesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/resources/';
};

export type AccessControlResourcesListResponses = {
    200: PaginatedResourceUserPermissionListReadable;
};

export type AccessControlResourcesListResponse = AccessControlResourcesListResponses[keyof AccessControlResourcesListResponses];

export type AccessControlResourcesRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/resources/{id}/';
};

export type AccessControlResourcesRetrieveResponses = {
    200: ResourceUserPermissionReadable;
};

export type AccessControlResourcesRetrieveResponse = AccessControlResourcesRetrieveResponses[keyof AccessControlResourcesRetrieveResponses];

export type AccessControlUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/users/';
};

export type AccessControlUsersListResponses = {
    200: PaginatedResourceUserListReadable;
};

export type AccessControlUsersListResponse = AccessControlUsersListResponses[keyof AccessControlUsersListResponses];

export type AccessControlUsersCreateData = {
    body: ResourceUserWritable;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/users/';
};

export type AccessControlUsersCreateResponses = {
    201: ResourceUserReadable;
};

export type AccessControlUsersCreateResponse = AccessControlUsersCreateResponses[keyof AccessControlUsersCreateResponses];

export type AccessControlUsersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlUsersDestroyResponse = AccessControlUsersDestroyResponses[keyof AccessControlUsersDestroyResponses];

export type AccessControlUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersRetrieveResponses = {
    200: ResourceUserReadable;
};

export type AccessControlUsersRetrieveResponse = AccessControlUsersRetrieveResponses[keyof AccessControlUsersRetrieveResponses];

export type AccessControlUsersWithGroupCreateData = {
    body: ResourceUserWritable;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/users/with_group/';
};

export type AccessControlUsersWithGroupCreateResponses = {
    200: ResourceUserReadable;
};

export type AccessControlUsersWithGroupCreateResponse = AccessControlUsersWithGroupCreateResponses[keyof AccessControlUsersWithGroupCreateResponses];

export type AuthApiaccessDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthApiaccessDestroyResponse = AuthApiaccessDestroyResponses[keyof AuthApiaccessDestroyResponses];

export type AuthApiaccessRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthApiaccessCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLoginCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login/';
};

export type AuthLoginCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout/';
};

export type AuthLogoutCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLogoutallCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logoutall/';
};

export type AuthLogoutallCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthRefreshCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh/';
};

export type AuthRefreshCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
    url: '/api/v1/auth/sessions/';
};

export type AuthSessionsListResponses = {
    200: Array<TokenSessionsReadable>;
};

export type AuthSessionsListResponse = AuthSessionsListResponses[keyof AuthSessionsListResponses];

export type AuthSessionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this auth token.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/auth/sessions/{id}/';
};

export type AuthSessionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthSessionsDestroyResponse = AuthSessionsDestroyResponses[keyof AuthSessionsDestroyResponses];

export type GroupsListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        hidden?: boolean;
        id?: string;
        id__exact?: string;
        id__in?: string;
        name?: string;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        /**
         * Number of results to return per page.
         */
        size?: number;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/';
};

export type GroupsListResponses = {
    200: PaginatedCustomGroupListReadable;
};

export type GroupsListResponse = GroupsListResponses[keyof GroupsListResponses];

export type GroupsCreateData = {
    body: CustomGroupWritable;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/';
};

export type GroupsCreateResponses = {
    201: CustomGroupReadable;
};

export type GroupsCreateResponse = GroupsCreateResponses[keyof GroupsCreateResponses];

export type GroupsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GroupsDestroyResponse = GroupsDestroyResponses[keyof GroupsDestroyResponses];

export type GroupsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsRetrieveResponses = {
    200: CustomGroupReadable;
};

export type GroupsRetrieveResponse = GroupsRetrieveResponses[keyof GroupsRetrieveResponses];

export type GroupsPartialUpdateData = {
    body?: PatchedCustomGroupWritable;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsPartialUpdateResponses = {
    200: CustomGroupReadable;
};

export type GroupsPartialUpdateResponse = GroupsPartialUpdateResponses[keyof GroupsPartialUpdateResponses];

export type GroupsUpdateData = {
    body: CustomGroupWritable;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsUpdateResponses = {
    200: CustomGroupReadable;
};

export type GroupsUpdateResponse = GroupsUpdateResponses[keyof GroupsUpdateResponses];

export type UpdateMembersData = {
    body?: {
        members?: Array<string>;
    };
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/members/';
};

export type UpdateMembersResponses = {
    200: Array<string>;
};

export type UpdateMembersResponse = UpdateMembersResponses[keyof UpdateMembersResponses];

export type OrganizationsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/organizations/';
};

export type OrganizationsListResponses = {
    200: PaginatedOrganizationListReadable;
};

export type OrganizationsListResponse = OrganizationsListResponses[keyof OrganizationsListResponses];

export type OrganizationsCreateData = {
    body: OrganizationWritable;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type OrganizationsCreateResponses = {
    201: OrganizationReadable;
};

export type OrganizationsCreateResponse = OrganizationsCreateResponses[keyof OrganizationsCreateResponses];

export type OrganizationsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrganizationsDestroyResponse = OrganizationsDestroyResponses[keyof OrganizationsDestroyResponses];

export type OrganizationsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsRetrieveResponses = {
    200: OrganizationReadable;
};

export type OrganizationsRetrieveResponse = OrganizationsRetrieveResponses[keyof OrganizationsRetrieveResponses];

export type OrganizationsPartialUpdateData = {
    body?: PatchedOrganizationWritable;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsPartialUpdateResponses = {
    200: OrganizationReadable;
};

export type OrganizationsPartialUpdateResponse = OrganizationsPartialUpdateResponses[keyof OrganizationsPartialUpdateResponses];

export type OrganizationsUpdateData = {
    body: OrganizationWritable;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsUpdateResponses = {
    200: OrganizationReadable;
};

export type OrganizationsUpdateResponse = OrganizationsUpdateResponses[keyof OrganizationsUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        date_joined?: string;
        email?: string;
        email__contains?: string;
        first_name?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name?: string;
        last_name__contains?: string;
        last_name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/users/';
};

export type UsersListResponses = {
    200: PaginatedCustomUserListReadable;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: CustomUserWritable;
    path?: never;
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/';
};

export type UsersCreateResponses = {
    201: CustomUserReadable;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: CustomUserReadable;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedCustomUserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: CustomUserReadable;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: CustomUserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersUpdateResponses = {
    200: CustomUserReadable;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: CustomUserReadable;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};