// This file is auto-generated by @hey-api/openapi-ts

export type CustomGroup = {
    readonly id: string;
    readonly member_count: number;
    readonly members: Array<CustomMembers>;
    name: string;
    description?: string | null;
    hidden?: boolean;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type CustomMembers = {
    readonly id: string;
    readonly email: string;
    readonly avatar: string;
    readonly first_name: string;
    readonly last_name: string;
    readonly date_joined: string;
};

export type CustomUser = {
    readonly id: string;
    /**
     * Email address
     */
    email: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
    readonly groups: Array<CustomUserGroup>;
    readonly date_joined: string;
};

export type CustomUserGroup = {
    readonly id: string;
    readonly name: string;
};

export type Environment = {
    readonly id: string;
    name: string;
    readonly created: string;
    readonly updated: string;
    description?: string | null;
    url: string;
    pg_url: string;
    parent_org: string;
    auth_user: string;
};

export type Nested = {
    readonly id: string;
    name: string;
    description?: string | null;
    hidden?: boolean;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type Organization = {
    readonly id: string;
    name: string;
    avatar?: string | null;
    host: string;
    readonly created: string;
    readonly updated: string;
    root: Nested;
};

export type PaginatedCustomGroupList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomGroup>;
};

export type PaginatedCustomUserList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<CustomUser>;
};

export type PaginatedEnvironmentList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Environment>;
};

export type PaginatedOrganizationList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<Organization>;
};

export type PaginatedResourcePermissionList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourcePermission>;
};

export type PaginatedResourceUserGroupList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserGroup>;
};

export type PaginatedResourceUserList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUser>;
};

export type PaginatedResourceUserPermissionsList = {
    count: number;
    next?: number | null;
    previous?: number | null;
    results: Array<ResourceUserPermissions>;
};

export type PatchedCustomGroup = {
    readonly id?: string;
    readonly member_count?: number;
    readonly members?: Array<CustomMembers>;
    name?: string;
    description?: string | null;
    hidden?: boolean;
    readonly created?: string;
    readonly updated?: string;
    parent?: string | null;
};

export type PatchedCustomUser = {
    readonly id?: string;
    /**
     * Email address
     */
    email?: string;
    avatar?: string | null;
    first_name?: string;
    last_name?: string;
    /**
     * Active
     */
    is_active?: boolean;
    readonly groups?: Array<CustomUserGroup>;
    readonly date_joined?: string;
};

export type PatchedEnvironment = {
    readonly id?: string;
    name?: string;
    readonly created?: string;
    readonly updated?: string;
    description?: string | null;
    url?: string;
    pg_url?: string;
    parent_org?: string;
    auth_user?: string;
};

export type PatchedOrganization = {
    readonly id?: string;
    name?: string;
    avatar?: string | null;
    host?: string;
    readonly created?: string;
    readonly updated?: string;
    root?: Nested;
};

export type PatchedResourcePermission = {
    readonly id?: string;
    resource_id?: string;
    inherit_from_parent?: boolean;
    readonly created?: string;
    readonly updated?: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource?: string;
    group?: string | null;
};

export type PatchedResourceUser = {
    readonly id?: string;
    user_id?: string;
    readonly created?: string;
    environment?: string;
    groups?: Array<string>;
};

export type PatchedResourceUserGroup = {
    readonly id?: string;
    name?: string;
    description?: string | null;
    readonly created?: string;
    readonly updated?: string;
    parent?: string | null;
};

export type ResourcePermission = {
    readonly id: string;
    resource_id: string;
    inherit_from_parent?: boolean;
    readonly created: string;
    readonly updated: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    children_permissions?: string | null;
    user_resource: string;
    group?: string | null;
};

export type ResourceUser = {
    readonly id: string;
    user_id: string;
    readonly created: string;
    environment: string;
    groups: Array<string>;
};

export type ResourceUserGroup = {
    readonly id: string;
    name: string;
    description?: string | null;
    readonly created: string;
    readonly updated: string;
    parent?: string | null;
};

export type ResourceUserPermissions = {
    readonly id: string;
    resource_id: string;
    can_create?: boolean | null;
    can_read?: boolean | null;
    can_update?: boolean | null;
    can_delete?: boolean | null;
    user_id?: string | null;
    environment: string;
};

/**
 * Used in :class:`durin.views.TokenSessionsViewSet`.
 *
 * .. versionadded:: 1.0.0
 */
export type TokenSessions = {
    readonly id: number;
    /**
     * A unique identification name for the client.
     */
    readonly client: string;
    readonly created: string;
    readonly expiry: string;
    /**
     * Dynamic property that returns ``True`` if token has expired,
     * otherwise ``False``.
     */
    readonly has_expired: boolean;
    readonly is_current: boolean;
    expires_in_str: string;
};

export type AccessControlGroupsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/groups/';
};

export type AccessControlGroupsListResponses = {
    200: PaginatedResourceUserGroupList;
};

export type AccessControlGroupsListResponse = AccessControlGroupsListResponses[keyof AccessControlGroupsListResponses];

export type AccessControlGroupsCreateData = {
    body: ResourceUserGroup;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/groups/';
};

export type AccessControlGroupsCreateResponses = {
    201: ResourceUserGroup;
};

export type AccessControlGroupsCreateResponse = AccessControlGroupsCreateResponses[keyof AccessControlGroupsCreateResponses];

export type AccessControlGroupsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlGroupsDestroyResponse = AccessControlGroupsDestroyResponses[keyof AccessControlGroupsDestroyResponses];

export type AccessControlGroupsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsRetrieveResponses = {
    200: ResourceUserGroup;
};

export type AccessControlGroupsRetrieveResponse = AccessControlGroupsRetrieveResponses[keyof AccessControlGroupsRetrieveResponses];

export type AccessControlGroupsPartialUpdateData = {
    body?: PatchedResourceUserGroup;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsPartialUpdateResponses = {
    200: ResourceUserGroup;
};

export type AccessControlGroupsPartialUpdateResponse = AccessControlGroupsPartialUpdateResponses[keyof AccessControlGroupsPartialUpdateResponses];

export type AccessControlGroupsUpdateData = {
    body: ResourceUserGroup;
    path: {
        /**
         * A UUID string identifying this resource user group.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/groups/{id}/';
};

export type AccessControlGroupsUpdateResponses = {
    200: ResourceUserGroup;
};

export type AccessControlGroupsUpdateResponse = AccessControlGroupsUpdateResponses[keyof AccessControlGroupsUpdateResponses];

export type AccessControlPermissionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/permissions/';
};

export type AccessControlPermissionsListResponses = {
    200: PaginatedResourcePermissionList;
};

export type AccessControlPermissionsListResponse = AccessControlPermissionsListResponses[keyof AccessControlPermissionsListResponses];

export type AccessControlPermissionsCreateData = {
    body: ResourcePermission;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/permissions/';
};

export type AccessControlPermissionsCreateResponses = {
    201: ResourcePermission;
};

export type AccessControlPermissionsCreateResponse = AccessControlPermissionsCreateResponses[keyof AccessControlPermissionsCreateResponses];

export type AccessControlPermissionsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlPermissionsDestroyResponse = AccessControlPermissionsDestroyResponses[keyof AccessControlPermissionsDestroyResponses];

export type AccessControlPermissionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsRetrieveResponses = {
    200: ResourcePermission;
};

export type AccessControlPermissionsRetrieveResponse = AccessControlPermissionsRetrieveResponses[keyof AccessControlPermissionsRetrieveResponses];

export type AccessControlPermissionsPartialUpdateData = {
    body?: PatchedResourcePermission;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsPartialUpdateResponses = {
    200: ResourcePermission;
};

export type AccessControlPermissionsPartialUpdateResponse = AccessControlPermissionsPartialUpdateResponses[keyof AccessControlPermissionsPartialUpdateResponses];

export type AccessControlPermissionsUpdateData = {
    body: ResourcePermission;
    path: {
        /**
         * A UUID string identifying this resource permission.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/permissions/{id}/';
};

export type AccessControlPermissionsUpdateResponses = {
    200: ResourcePermission;
};

export type AccessControlPermissionsUpdateResponse = AccessControlPermissionsUpdateResponses[keyof AccessControlPermissionsUpdateResponses];

export type AccessControlResourcesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/resources/';
};

export type AccessControlResourcesListResponses = {
    200: PaginatedResourceUserPermissionsList;
};

export type AccessControlResourcesListResponse = AccessControlResourcesListResponses[keyof AccessControlResourcesListResponses];

export type AccessControlResourcesRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user permissions.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/resources/{id}/';
};

export type AccessControlResourcesRetrieveResponses = {
    200: ResourceUserPermissions;
};

export type AccessControlResourcesRetrieveResponse = AccessControlResourcesRetrieveResponses[keyof AccessControlResourcesRetrieveResponses];

export type AccessControlUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/access-control/users/';
};

export type AccessControlUsersListResponses = {
    200: PaginatedResourceUserList;
};

export type AccessControlUsersListResponse = AccessControlUsersListResponses[keyof AccessControlUsersListResponses];

export type AccessControlUsersCreateData = {
    body: ResourceUser;
    path?: never;
    query?: never;
    url: '/api/v1/access-control/users/';
};

export type AccessControlUsersCreateResponses = {
    201: ResourceUser;
};

export type AccessControlUsersCreateResponse = AccessControlUsersCreateResponses[keyof AccessControlUsersCreateResponses];

export type AccessControlUsersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AccessControlUsersDestroyResponse = AccessControlUsersDestroyResponses[keyof AccessControlUsersDestroyResponses];

export type AccessControlUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersRetrieveResponses = {
    200: ResourceUser;
};

export type AccessControlUsersRetrieveResponse = AccessControlUsersRetrieveResponses[keyof AccessControlUsersRetrieveResponses];

export type AccessControlUsersPartialUpdateData = {
    body?: PatchedResourceUser;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersPartialUpdateResponses = {
    200: ResourceUser;
};

export type AccessControlUsersPartialUpdateResponse = AccessControlUsersPartialUpdateResponses[keyof AccessControlUsersPartialUpdateResponses];

export type AccessControlUsersUpdateData = {
    body: ResourceUser;
    path: {
        /**
         * A UUID string identifying this resource user.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/access-control/users/{id}/';
};

export type AccessControlUsersUpdateResponses = {
    200: ResourceUser;
};

export type AccessControlUsersUpdateResponse = AccessControlUsersUpdateResponses[keyof AccessControlUsersUpdateResponses];

export type AuthApiaccessDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthApiaccessDestroyResponse = AuthApiaccessDestroyResponses[keyof AuthApiaccessDestroyResponses];

export type AuthApiaccessRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthApiaccessCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/apiaccess/';
};

export type AuthApiaccessCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLoginCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login/';
};

export type AuthLoginCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout/';
};

export type AuthLogoutCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthLogoutallCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logoutall/';
};

export type AuthLogoutallCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthRefreshCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh/';
};

export type AuthRefreshCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AuthSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
    url: '/api/v1/auth/sessions/';
};

export type AuthSessionsListResponses = {
    200: Array<TokenSessions>;
};

export type AuthSessionsListResponse = AuthSessionsListResponses[keyof AuthSessionsListResponses];

export type AuthSessionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this auth token.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/auth/sessions/{id}/';
};

export type AuthSessionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AuthSessionsDestroyResponse = AuthSessionsDestroyResponses[keyof AuthSessionsDestroyResponses];

export type EnvironmentsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/environments/';
};

export type EnvironmentsListResponses = {
    200: PaginatedEnvironmentList;
};

export type EnvironmentsListResponse = EnvironmentsListResponses[keyof EnvironmentsListResponses];

export type EnvironmentsCreateData = {
    body: Environment;
    path?: never;
    query?: never;
    url: '/api/v1/environments/';
};

export type EnvironmentsCreateResponses = {
    201: Environment;
};

export type EnvironmentsCreateResponse = EnvironmentsCreateResponses[keyof EnvironmentsCreateResponses];

export type EnvironmentsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/environments/{id}/';
};

export type EnvironmentsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type EnvironmentsDestroyResponse = EnvironmentsDestroyResponses[keyof EnvironmentsDestroyResponses];

export type EnvironmentsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/environments/{id}/';
};

export type EnvironmentsRetrieveResponses = {
    200: Environment;
};

export type EnvironmentsRetrieveResponse = EnvironmentsRetrieveResponses[keyof EnvironmentsRetrieveResponses];

export type EnvironmentsPartialUpdateData = {
    body?: PatchedEnvironment;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/environments/{id}/';
};

export type EnvironmentsPartialUpdateResponses = {
    200: Environment;
};

export type EnvironmentsPartialUpdateResponse = EnvironmentsPartialUpdateResponses[keyof EnvironmentsPartialUpdateResponses];

export type EnvironmentsUpdateData = {
    body: Environment;
    path: {
        /**
         * A UUID string identifying this environment.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/environments/{id}/';
};

export type EnvironmentsUpdateResponses = {
    200: Environment;
};

export type EnvironmentsUpdateResponse = EnvironmentsUpdateResponses[keyof EnvironmentsUpdateResponses];

export type GroupsListData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        hidden?: boolean;
        id?: string;
        id__exact?: string;
        id__in?: string;
        name?: string;
        name__contains?: string;
        name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        parent?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        /**
         * Number of results to return per page.
         */
        size?: number;
        updated?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/';
};

export type GroupsListResponses = {
    200: PaginatedCustomGroupList;
};

export type GroupsListResponse = GroupsListResponses[keyof GroupsListResponses];

export type GroupsCreateData = {
    body: CustomGroup;
    path?: never;
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/';
};

export type GroupsCreateResponses = {
    201: CustomGroup;
};

export type GroupsCreateResponse = GroupsCreateResponses[keyof GroupsCreateResponses];

export type GroupsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GroupsDestroyResponse = GroupsDestroyResponses[keyof GroupsDestroyResponses];

export type GroupsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsRetrieveResponses = {
    200: CustomGroup;
};

export type GroupsRetrieveResponse = GroupsRetrieveResponses[keyof GroupsRetrieveResponses];

export type GroupsPartialUpdateData = {
    body?: PatchedCustomGroup;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsPartialUpdateResponses = {
    200: CustomGroup;
};

export type GroupsPartialUpdateResponse = GroupsPartialUpdateResponses[keyof GroupsPartialUpdateResponses];

export type GroupsUpdateData = {
    body: CustomGroup;
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/';
};

export type GroupsUpdateResponses = {
    200: CustomGroup;
};

export type GroupsUpdateResponse = GroupsUpdateResponses[keyof GroupsUpdateResponses];

export type UpdateMembersData = {
    body?: {
        members?: Array<string>;
    };
    path: {
        /**
         * A UUID string identifying this custom group.
         */
        id: string;
    };
    query?: {
        created__gte?: string;
        created__lte?: string;
        description__contains?: string;
        description__exact?: string;
        id__exact?: string;
        id__in?: string;
        name__contains?: string;
        name__exact?: string;
        parent__exact?: string;
        parent__in?: string;
        parent__isnull?: string;
        updated__gte?: string;
        updated__lte?: string;
    };
    url: '/api/v1/groups/{id}/members/';
};

export type UpdateMembersResponses = {
    200: Array<string>;
};

export type UpdateMembersResponse = UpdateMembersResponses[keyof UpdateMembersResponses];

export type OrganizationsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/organizations/';
};

export type OrganizationsListResponses = {
    200: PaginatedOrganizationList;
};

export type OrganizationsListResponse = OrganizationsListResponses[keyof OrganizationsListResponses];

export type OrganizationsCreateData = {
    body: Organization;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type OrganizationsCreateResponses = {
    201: Organization;
};

export type OrganizationsCreateResponse = OrganizationsCreateResponses[keyof OrganizationsCreateResponses];

export type OrganizationsDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrganizationsDestroyResponse = OrganizationsDestroyResponses[keyof OrganizationsDestroyResponses];

export type OrganizationsRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsRetrieveResponses = {
    200: Organization;
};

export type OrganizationsRetrieveResponse = OrganizationsRetrieveResponses[keyof OrganizationsRetrieveResponses];

export type OrganizationsPartialUpdateData = {
    body?: PatchedOrganization;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsPartialUpdateResponses = {
    200: Organization;
};

export type OrganizationsPartialUpdateResponse = OrganizationsPartialUpdateResponses[keyof OrganizationsPartialUpdateResponses];

export type OrganizationsUpdateData = {
    body: Organization;
    path: {
        /**
         * A UUID string identifying this organization.
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{id}/';
};

export type OrganizationsUpdateResponses = {
    200: Organization;
};

export type OrganizationsUpdateResponse = OrganizationsUpdateResponses[keyof OrganizationsUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        date_joined?: string;
        email?: string;
        email__contains?: string;
        first_name?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name?: string;
        last_name__contains?: string;
        last_name__exact?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        size?: number;
    };
    url: '/api/v1/users/';
};

export type UsersListResponses = {
    200: PaginatedCustomUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: CustomUser;
    path?: never;
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/';
};

export type UsersCreateResponses = {
    201: CustomUser;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: CustomUser;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedCustomUser;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: CustomUser;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: CustomUser;
    path: {
        /**
         * A UUID string identifying this user.
         */
        id: string;
    };
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/{id}/';
};

export type UsersUpdateResponses = {
    200: CustomUser;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        date_joined?: string;
        email__contains?: string;
        first_name__contains?: string;
        first_name__exact?: string;
        groups__id__exact?: string;
        groups__id__in?: string;
        id__exact?: string;
        id__in?: string;
        is_active?: string;
        last_name__contains?: string;
        last_name__exact?: string;
    };
    url: '/api/v1/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: CustomUser;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};