# Generated by Django 5.2.1 on 2025-08-19 21:42

import access_control.fields
import access_control.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(verbose_name="name")),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("url", models.URLField()),
                ("pg_url", access_control.fields.CustomURLField()),
                ("default_can_read", models.BooleanField(default=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_environment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
            managers=[
                ("objects", access_control.models.EnvironmentManager()),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("resource_id", models.CharField()),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access_control.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
            managers=[
                ("objects", access_control.models.ResourceManager()),
            ],
        ),
        migrations.CreateModel(
            name="ResourceUserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(verbose_name="name")),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_groups",
                        to="access_control.environment",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="access_control.resourceusergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "unique_together": {("name", "environment")},
            },
            managers=[
                ("objects", access_control.models.ResourceUserGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="ResourceUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField()),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_users",
                        to="access_control.environment",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        null=True,
                        related_name="members",
                        to="access_control.resourceusergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "unique_together": {("user_id", "environment")},
            },
            managers=[
                ("objects", access_control.models.ResourceUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="default_resource_group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="access_control.resourceusergroup",
            ),
        ),
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("can_create", models.BooleanField(null=True)),
                ("can_read", models.BooleanField(null=True)),
                ("can_update", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("inherit_from_parent", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, null=True, verbose_name="names")),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access_control.environment",
                    ),
                ),
                (
                    "parent_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_permissions",
                        to="access_control.resourcepermission",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions",
                        to="access_control.resource",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="access_control.resourceusergroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent_permission"],
                        name="access_cont_parent__220d33_idx",
                    ),
                    models.Index(
                        fields=["group"], name="access_cont_group_i_ef4353_idx"
                    ),
                ],
            },
            managers=[
                ("objects", access_control.models.ResourcePermissionManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together={("name", "parent_org")},
        ),
        migrations.CreateModel(
            name="ResourceUserPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_create", models.BooleanField()),
                ("can_read", models.BooleanField()),
                ("can_update", models.BooleanField()),
                ("can_delete", models.BooleanField()),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="access_control.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access_control.resourceuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="access_cont_user_id_7af0f5_idx")
                ],
            },
            managers=[
                ("objects", access_control.models.ResourceUserPermissionManager()),
            ],
        ),
    ]
